// Generate and store 100 enemies.
// 
// Each enemy should have the following properties:
// 
// type
// hitPoints
// defense
// The type should be randomly selected among the following types:
// 
// Ancient Dragon
// Prowler
// Mighty Grunt
// 
// The hitPoints property should be generated randomly according to the // following criteria:
// 
// If the type is Ancient Dragon then the hitPoints should be between 80-  // 100
// If the type is Prowler then the hitPoints should be between 50-79
// If the type is Mighty Grunt then the hitPoints should be between 20-49
// 
// The enemy's defense is generated by multiplying the hitPoints by 3
        
var enemies = [];    

function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}                 
  
                      
function Enemy(type, hitPoints, defense) {                   
    this.type = determineType();
    this.hitPoints =determineHitPoints();
    this.defense = this.hitPoints * 3;
}
    
    
function determineType() {
    var enemyTypes = ["Ancient Dragon", "Prowler", "Mighty Grunt"];
    var rand = getRandomInt(0, 2);
    return enemyTypes[rand];
}
   
    
function determineHitPoints(type) {
    if (type === "Ancient Dragon") {
         return getRandomInt(80, 100);
    } else if(type === "Prowler"){
         return getRandomInt(50, 79);
     } else(type === "Mighty Grunt") 
        return getRandomInt(20, 49);
}
 
function enemy() {
    this.type = determineType();
    this.hitPoints = determineHitPoints(this.type);
    this.defense = this.hitPoints * 3;
}

function makeEnemies(num) {
    for(var i = 0; i < num; i++) {
        var newEnemy = new Enemy();
        enemies.push(newEnemy);
    }
}
makeEnemies(10);
console.log(enemies);

                      
                      
      
                      
                      
                      